import { z } from "zod";
import type { McpServer } from "../../adapters/inbound/mcp/legacy-sdk-bridge.js";

const context = { correlationId: z.string().min(1).optional(), taskId: z.string().optional() };
const cwd = z.string().default(".");


/** Schema registration only. Legacy direct Git callbacks are retired. */
export function registerGitTools(server: McpServer) {
  server.registerTool("git_status", { title: "Git Status", description: "🔀 GIT (read) — Working tree status: staged, unstaged, untracked + branch info.\n\nExample: { \"cwd\": \".\" }", annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true }, inputSchema: z.object({ cwd, ...context }) }, async () => { throw new Error("r2_legacy_direct_callback_retired"); });
  server.registerTool("git_diff", { title: "Git Diff", description: "🔀 GIT (read) — Show unstaged changes, or staged with staged=true (what a commit would include).\n\nExamples: { \"cwd\": \".\" } · { \"staged\": true }", annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true }, inputSchema: z.object({ cwd, staged: z.boolean().default(false), ...context }) }, async () => { throw new Error("r2_legacy_direct_callback_retired"); });
  server.registerTool("git_clone", { title: "Git Clone", description: "🔀 GIT (mutation, needs approval) — Clone a public HTTPS repo (no embedded credentials) into the workspace.\n\nExample: { \"url\": \"https://github.com/user/repo\", \"path\": \"my-project\" }", annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true }, inputSchema: z.object({ url: z.url(), path: z.string(), ...context }) }, async () => { throw new Error("r2_legacy_direct_callback_retired"); });
  server.registerTool("git_commit", { title: "Git Commit", description: "🔀 GIT (mutation, needs approval) — Commit staged changes. Check with git_diff(staged=true) first. Message 1-500 chars; fails with git_identity_missing if user.name/email unset.\n\nExample: { \"message\": \"feat: add login page\", \"cwd\": \".\" }", annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false }, inputSchema: z.object({ cwd, message: z.string().min(1).max(500), ...context }) }, async () => { throw new Error("r2_legacy_direct_callback_retired"); });
  server.registerTool("git_branch", { title: "Git Branch", description: "🔀 GIT (mutation, needs approval) — Create a branch without switching. Use git_checkout to switch.\n\nExample: { \"name\": \"feature/login\" }", annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false }, inputSchema: z.object({ cwd, name: z.string(), ...context }) }, async () => { throw new Error("r2_legacy_direct_callback_retired"); });
  server.registerTool("git_checkout", { title: "Git Checkout", description: "🔀 GIT (mutation, needs approval) — Switch branch; create=true to create-and-switch.\n\nExamples: { \"name\": \"main\" } · { \"name\": \"feature/x\", \"create\": true }", annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false }, inputSchema: z.object({ cwd, name: z.string(), create: z.boolean().default(false), ...context }) }, async () => { throw new Error("r2_legacy_direct_callback_retired"); });
  server.registerTool("git_add", { title: "Git Add", description: "🔀 GIT (mutation, needs approval) — Stage files for commit. paths=[\".\"] stages everything.\n\nExample: { \"paths\": [\"src/file.ts\"] }", annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false }, inputSchema: z.object({ cwd, paths: z.array(z.string()).min(1).max(100), ...context }) }, async () => { throw new Error("r2_legacy_direct_callback_retired"); });
  server.registerTool("git_init", { title: "Git Init", description: "🔀 GIT (mutation, needs approval) — Initialize a new git repository. Default branch: main. Requires approval through an approved task step, like other git mutations.\n\nExample: { \"path\": \"D:/Projects/my-new-project\" }", annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false }, inputSchema: z.object({ path: z.string(), initialBranch: z.string().default("main"), ...context }) }, async () => { throw new Error("r2_legacy_direct_callback_retired"); });
  server.registerTool("git_log", { title: "Git Log", description: "🔀 GIT (read) — Recent commit history, one line per commit with refs. limit 1-100 (default 20).\n\nExample: { \"limit\": 10 }", annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true }, inputSchema: z.object({ cwd, limit: z.number().int().min(1).max(100).default(20), ...context }) }, async () => { throw new Error("r2_legacy_direct_callback_retired"); });
}
